-- Careers table for job postings
CREATE TABLE IF NOT EXISTS careers (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title_az TEXT NOT NULL,
    title_en TEXT NOT NULL,
    title_ru TEXT NOT NULL,
    description_az TEXT NOT NULL,
    description_en TEXT NOT NULL,
    description_ru TEXT NOT NULL,
    salary_range_az TEXT,
    salary_range_en TEXT,
    salary_range_ru TEXT,
    work_hours_az TEXT NOT NULL,
    work_hours_en TEXT NOT NULL,
    work_hours_ru TEXT NOT NULL,
    category_az TEXT NOT NULL,
    category_en TEXT NOT NULL,
    category_ru TEXT NOT NULL,
    tags_az TEXT,
    tags_en TEXT,
    tags_ru TEXT,
    email TEXT NOT NULL,
    created_date DATE DEFAULT CURRENT_DATE,
    expiry_date DATE,
    is_active BOOLEAN DEFAULT 1,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Insert sample career data
INSERT INTO careers (
    title_az, title_en, title_ru,
    description_az, description_en, description_ru,
    salary_range_az, salary_range_en, salary_range_ru,
    work_hours_az, work_hours_en, work_hours_ru,
    category_az, category_en, category_ru,
    tags_az, tags_en, tags_ru,
    email, expiry_date
) VALUES 
(
    'Layihə Meneceri',
    'Project Manager',
    'Менеджер Проектов',
    'Bizim komandamıza qoşulmaq istəyən təcrübəli layihə meneceri axtarırıq. Candidate müxtəlif layihələri idarə etmək və komanda ilə əlaqə saxlamaq bacarığına sahib olmalıdır.',
    'We are looking for an experienced project manager to join our team. The candidate should have the ability to manage various projects and coordinate with the team.',
    'Мы ищем опытного менеджера проектов для присоединения к нашей команде. Кандидат должен уметь управлять различными проектами и координировать работу команды.',
    '3000-5000 AZN',
    '3000-5000 AZN',
    '3000-5000 AZN',
    'Tam vaxt (09:00-18:00)',
    'Full time (09:00-18:00)',
    'Полный рабочий день (09:00-18:00)',
    'İdarəetmə',
    'Management',
    'Управление',
    'layihə,menecment,komanda',
    'project,management,team',
    'проект,управление,команда',
    'hr@caspiaindustry.az',
    '2025-12-31'
),
(
    'Satış Mütəxəssisi',
    'Sales Specialist',
    'Специалист по Продажам',
    'Müştərilərlə əlaqə saxlamaq və satış artırmaq üçün dinamik satış mütəxəssisi axtarırıq. B2B satış təcrübəsi olan namizədlərə üstünlük veriləcək.',
    'We are looking for a dynamic sales specialist to maintain customer relations and increase sales. Preference will be given to candidates with B2B sales experience.',
    'Мы ищем динамичного специалиста по продажам для поддержания отношений с клиентами и увеличения продаж. Предпочтение будет отдано кандидатам с опытом B2B продаж.',
    'Razılaşma yolu ilə',
    'Negotiable',
    'По договоренности',
    'Tam vaxt',
    'Full time',
    'Полный рабочий день',
    'Satış',
    'Sales',
    'Продажи',
    'satış,müştəri,B2B',
    'sales,customer,B2B',
    'продажи,клиент,B2B',
    'sales@caspiaindustry.az',
    '2025-12-15'
);